#! /usr/bin/env node

var root = require('rootpath')(__dirname, '..')

var schema = require(root('schema/schema'))

schema = require('./lib/mustz')(schema)

var fs = require('fs-sync')

var csst = fs.read(root('schema/css.template'))

var render = require('mustache').render

var css = render(csst, schema)

fs.write(root('gen/gen.css'), css)
