#! /usr/bin/env node

var root = require('rootpath')(__dirname, '..')

var schema = require(root('schema/schema'))

schema = require('./lib/mustz')(schema)

var fs = require('fs-sync')

var csst = fs.read(root('template/css.mst'))

var mustache = require('mustache')

var css = mustache.render(csst, schema)

fs.write(root('gen/gen.css'), css)

var jade = require('jade')

var htmlt = fs.read(root('template/index.jade'))

var html = jade.render(htmlt,
{
	pretty: true,
	schema: schema
})

fs.write(root('gen/index.html'), html)

fs.copy(root('template/static.css'), root('gen/static.css'), { force: true })
