#! /usr/bin/env node

var template =
[
	'black',
	'red',
	'green',
	'yellow',
	'blue',
	'magenta',
	'cyan',
	'white'
]

var schema = require('../schema/schema')

/* bg only, because of xfce only accepts 16 colors, not {fg/bg} */
var base16 = schema.base16.colors.bg

var seq = []

seq = template.reduce(function (memo, name)
{
	return memo.concat([ base16[name].normal.hex() ])
},
seq)

seq = template.reduce(function (memo, name)
{
	return memo.concat([ base16[name].bright.hex() ])
},
seq)

seq = seq.join(';')

seq = 'ColorPalette=' + seq

process.stdout.write(seq)
