#! /usr/bin/env node

var schema = require('../schema/schema')

var traverse = require('traverse')

var dump = JSON.stringify

schema = traverse.clone(schema)
schema = traverse(schema).forEach(function (it)
{
	if (it.constructor.name === 'Color') /* this lib is a naughty one */
	{
		this.update(it.css())
	}
})

schema = dump(schema, null, '  ')

process.stdout.write(schema)
